### ISSUE TITLE
relation to circle loss

### ISSUE THREAD

**Issue by ShengyuH** [jiamings/ml-cpc#1]
hi Jiaming,

Thanks for your nice work. I find you didn't cite Circle loss(https://arxiv.org/abs/2002.10857) in your paper. But for me the reweighting scheme is quite similar to circle loss, they also reweight negative samples by their distances to the optimum. 

Can you share some ideas about the comparison between these two, or this is just my misunderstanding and they are totally different.

Best,
Shengyu

**Comment by jiamings** [comment]
Thanks for the pointer. If you reorganize the circle loss, you will see a term of logsumexp for the positive interactions in the numerator, which in our case is sumlogexp. Moreover, as we are interested in mutual information estimation (to which representation learning is an application), our objective is not specific to the inner products used in circle loss, and I don't think a circle loss-like formuation will give you a lower bound to mutual information.
